### ISSUE TITLE
nornir_netbox not working on macos Ventura + python3.11

### ISSUE THREAD

**Issue by vietsoulz** [wvandeun/nornir_netbox#45]
Hello, I am attempting to use nornir_netbox/napalm to perform dynamic inventory and automation but have been struggling to get nornir_netbox to work on macos ventura and python3.11.  Performing the same .py script works on a RHEL7 with python3.6.8.  It would be extremely helpful to run the .py script on macos instead of using it on the bastion host.  Thanks.

from nornir import InitNornir
from nornir_napalm.plugins.tasks import napalm_get, napalm_cli
from nornir.core.task import Task, Result
from nornir_utils.plugins.functions import print_result

output after running script from VS Code:

Traceback (most recent call last):
  File "/Volumes/tftproot/python/netmiko/nornir_netbox_v2.py", line 7, in <module>
    nr = InitNornir(
         ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nornir/init_nornir.py", line 72, in InitNornir
    inventory=load_inventory(config),
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nornir/init_nornir.py", line 18, in load_inventory
    InventoryPluginRegister.auto_register()
  File "/usr/local/lib/python3.11/site-packages/nornir/core/plugins/register.py", line 26, in auto_register
    self.register(entry_point.name, entry_point.load())
                                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/tftproot/python/netmiko/nornir_netbox.py", line 13, in <module>
    nr = InitNornir(
         ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nornir/init_nornir.py", line 72, in InitNornir
    inventory=load_inventory(config),
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nornir/init_nornir.py", line 18, in load_inventory
    InventoryPluginRegister.auto_register()
  File "/usr/local/lib/python3.11/site-packages/nornir/core/plugins/register.py", line 26, in auto_register
    self.register(entry_point.name, entry_point.load())
                                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1137, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nornir_netbox.plugins'; 'nornir_netbox' is not a package

**Comment by wvandeun** [comment]
It works for me on Ventura + 3.11 (3.11.3 installed through pyenv, not homebrew).

Can you please format the output in code blocks, because it's almost impossible to properly read the output you are pasting here.

I would probably need more details from your script to be able to help you any further. As well as how you installed everything and the contents of the directory in which the script is located.

**Comment by vietsoulz** [comment]
[nornir_netbox_ModuleNotFoundError.log](https://github.com/wvandeun/nornir_netbox/files/11682401/nornir_netbox_ModuleNotFoundError.log)

Please see attached file with the .py script and error thrown after launching the script.

**Comment by wvandeun** [comment]
Is there a `nornir_netbox.py` file in the same directory as the script `nornir_netbox_v2.py` ?
If so, can you please delete or rename that file and try again?

**Comment by vietsoulz** [comment]
That's interesting to know.  I moved nornir_netbox.py to a different folder and now able to run it directly via pyenv with python 3.11.3.  Thanks for the suggestion!

I am curious to know if there is an easy way to extract specific key,value pairs from the print_result function in nornir?

{ 'facts': { 'fqdn': 'hostname',
             'hostname': 'hostname',
             'model': 'Nexus9000 C93240YC-FX2 Chassis',
             'os_version': '9.3(5w)',
             'serial_number': 'XXXXXXXXX',
             'uptime': 25059417.0,
             'vendor': 'Cisco'}}

Any pointer?

**Comment by wvandeun** [comment]
You will have to look at how to process Nornir task results, https://nornir.readthedocs.io/en/latest/tutorial/task_results.html (see the programmatic way section).
