### ISSUE TITLE
Unable to use Nornir_Netbox 

### ISSUE THREAD

**Issue by heldgrind** [wvandeun/nornir_netbox#52]
Hello i would like to use nornir_netbox with nornir 3.4.1 but i have this error :

Script : 

`from nornir import InitNornir

nr = InitNornir(
    inventory={
        "plugin" : "NetBoxInventory2",
        "options": {
            "nb_url": "https://netbox.local",
            "nb_token": "sometoken",
        }
    }
)`

Error message :
`Traceback (most recent call last):
  File "C:\Users\Desktop\NETBOX\auto\Nornir\nornir_netbox.py", line 4, in <module>
    nr = InitNornir(
         ^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\nornir\init_nornir.py", line 72, in InitNornir
    inventory=load_inventory(config),
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\nornir\init_nornir.py", line 18, in load_inventory
    InventoryPluginRegister.auto_register()
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\nornir\core\plugins\register.py", line 26, in auto_register
    self.register(entry_point.name, entry_point.load())
                                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Desktop\NETBOX\auto\Nornir\nornir_netbox.py", line 4, in <module>
    nr = InitNornir(
         ^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\nornir\init_nornir.py", line 72, in InitNornir
    inventory=load_inventory(config),
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\nornir\init_nornir.py", line 18, in load_inventory
    InventoryPluginRegister.auto_register()
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\nornir\core\plugins\register.py", line 26, in auto_register
    self.register(entry_point.name, entry_point.load())
                                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1313, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nornir_netbox.plugins'; 'nornir_netbox' is not a package`

If someone have solution , thanks a lot !

**Comment by wvandeun** [comment]
You should rename your file to something else than `nornir_netbox`

**Comment by heldgrind** [comment]
yes you are right I did that and it works. A beginner's mistake haha thanks again !
